---
- hosts: all
  vars:
    user: yunabe
  tasks:
  - name: Include passwd.yml
    include_vars: vars/passwd.yml
  - name: Set user password
    user:
      name: "{{ user }}"
      password: "{{ passwd }}"
    become: yes
