---

# Install /bin/python to avoid "/usr/bin/python: not found" error.
# https://stackoverflow.com/a/41431540/4388164
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Install python
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: output
    changed_when: output.stdout != ""

- hosts: all
  vars:
    user: yunabe
  tasks:
  # By default, vars/passwd_secret.yml does not exist and vars/passwd_default.yml
  # set '*' to /etc/shadow and disable password-login.
  # To enable password, create vars/passwd_secret.yml and provide a hashed password.
  # To create a hashed password, follow the instruction and use passlib.
  # https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
  - name: Include passwd.yml
    include_vars: "{{ item }}"
    with_first_found:
      - vars/passwd_secret.yml
      - vars/passwd_default.yml
  - name: Set user password
    user:
      name: "{{ user }}"
      password: "{{ passwd }}"
    become: yes

- hosts: all
  vars:
    user: yunabe
  roles:
    - apt_common
    - chrome_remote_desktop
    - copy_sshkeys
    - dotfiles
    - python
    - apt_extended
    - apt_desktop
    - clone_git_repositories
