---
# Overwrite them with --extra-vars='{"user": "ubuntu"}'
# http://docs.ansible.com/ansible/playbooks_variables.html
#
# Notes:
# 1. The default `ubuntu` user are groups like `sudo` to have some previledges.
#    If you want to use another user name, please be careful about it.
# 2. `developer` group is created to demostrate how to add a group with ansible.
#     The group is not used for any real task.
- hosts: all
  vars:
    user: yunabe
  roles:
    - apt_common
    - dotfiles
    - copy_sshkeys
    - python
    - apt_extended
    - apt_desktop
    - clone_git_repositories

- hosts: all
  tasks:
  - name: Install jekyll to $HOME/.gem
    gem:
      name: jekyll
      state: latest

