# For some reason, this requires root permission.
- name: Use /bin/zsh as a log-in shell.
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: yes

# As far as I know, `~/` in the following rules can be ommited.
# I declared `~/` just to make the intention clearer.
- name: Clone config git repository
  git:
    repo: git@github.com:yunabe/linux-user-config.git
    dest: "~/config"
    accept_hostkey: yes
  tags:
    - git

# Ansible version of config/setup.sh.
- name: Link .emacs file
  file:
    path: "~/.emacs"
    src: "config/_emacs"
    state: link

- name: Link .zshrc file
  file:
    path: "~/.zsh.d"
    state: directory

- name: Make .zsh.d directory
  file:
    path: "~/.zshrc"
    src: "config/_zshrc"
    state: link

- name: Link .screenrc file
  file:
    path: "~/.screenrc"
    src: "config/_screenrc"
    state: link

- name: Link .gitconfig file
  file:
    path: "~/.gitconfig"
    src: "config/_gitconfig"
    state: link

- name: Link .npmrc file
  file:
    path: "~/.npmrc"
    src: "config/_npmrc"
    state: link

- name: Create .emacs.d directory
  file:
    path: ~/.emacs.d
    state: directory
    mode: 0700

- name: Link Cask file
  file:
    path: "~/.emacs.d/Cask"
    src: "../config/Cask"
    state: link

- name: Clone Cask repository
  git:
    repo: https://github.com/cask/cask.git
    dest: ~/.cask
    accept_hostkey: yes