- name: Use /bin/zsh as a log-in shell.
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Clone config git repository
  git:
    repo: git@github.com:yunabe/linux-user-config.git
    dest: /home/{{ user }}/config
    accept_hostkey: yes
  tags:
    - git

# Ansible version of config/setup.sh.
# TODO: Group these file modules as a role.
- name: Link .emacs file
  file:
    path: /home/{{ user }}/.emacs
    src: /home/{{ user }}/config/_emacs
    state: link

- name: Link .zshrc file
  file:
    path: /home/{{ user }}/.zsh.d
    state: directory

- name: Make .zsh.d directory
  file:
    path: /home/{{ user }}/.zshrc
    src: /home/{{ user }}/config/_zshrc
    state: link

- name: Link .screenrc file
  file:
    path: /home/{{ user }}/.screenrc
    src: /home/{{ user }}/config/_screenrc
    state: link

- name: Link .gitconfig file
  file:
    path: /home/{{ user }}/.gitconfig
    src: /home/{{ user }}/config/_gitconfig
    state: link
