- name: Install necessary packages
  become: yes
  apt:
    name: ['cinnamon-desktop-environment', 'gdebi-core', 'dbus-x11']
    force: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Create chrome-remote-desktop group
  become: yes
  group:
    name: chrome-remote-desktop

- name: Add {{ user }} to chrome-remote-desktop group
  become: yes
  user:
    name: "{{ user }}"
    append: yes
    groups: chrome-remote-desktop

- name: Check if screensaver lock-enabled is false
  shell: gsettings get org.cinnamon.desktop.screensaver lock-enabled
  register: screensaver_lock_enabled
  changed_when: false

# - name: Dump screensaver_lock_enabled
#   debug:
#     var: screensaver_lock_enabled

# Don't forget gbus-launch.
# https://stackoverflow.com/questions/30256153/gsettings-changes-are-not-working-over-ssh
- name: Disable screensaver lock-enabled.
  shell: dbus-launch gsettings set org.cinnamon.desktop.screensaver lock-enabled false
  when: screensaver_lock_enabled.stdout != "false"

- name: Check session idle-delay is off
  shell: gsettings get org.cinnamon.desktop.session idle-delay
  register: session_idle_delay
  changed_when: false

- name: Disable session idle-delay
  shell: dbus-launch gsettings set org.cinnamon.desktop.session idle-delay "uint32 0"
  when: session_idle_delay.stdout != "uint32 0"

# TODO: Detect the update of chrome-remote-desktop_current_amd64.deb.
- name: Check if chrome-remote-desktop is installed
  shell: dpkg-query -l chrome-remote-desktop
  changed_when: false
  ignore_errors: yes
  register: crd_installed

- name: Install chrome-remote-desktop
  become: yes
  shell: curl https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb --output crd_amd64.deb && gdebi -q -n crd_amd64.deb && rm -f crd_amd64.deb
  when: crd_installed.rc != 0
